export const initialValues = {
  packageID: "",
  packageName: "",
  packageDuration: "",
  packageDurationType: "",
  packageDescription: "",
  packageDestination: "",
  packagePrice: "",
  packageImage: "",
  peopleCount: "",
  packageAccommodationDetails: {
    accID: "",
    accName: "",
    accType: "",
    accPrice: "",
    accImage: "",
    accDuration: "",
    accDurationType: "",
  },
  packageTourDetails: {
    tourID: "",
    tourName: "",
    tourDestination: "",
    tourDescription: "",
    tourPrice: "",
    tourImage: "",
    tourGuide: "",
    tourSeason: "",
    tourAvailability: "",
  },
  packageTransportDetails: {
    transportID: "",
    transportType: "",
    rentalPrice: "",
    carCount: 0,
    dayCount: 0,
    ticketPrice: 0,
    ticketCount: 0,
  },
};
